name: trigger on event

on:
  repository_dispatch:
    types: [build, ext_trig]
  # schedule:
  #   - cron: "*/5 * * * *" 
  #push:
  pull_request:
    types: [closed, reopened, opened]

jobs:
    trigger-on-event:
      runs-on: ubuntu-latest
      steps:
        - name: echo string
          run: echo "this workflow was trigger by an event"