name: actions test

on:
  push:
    branches:
      - master

jobs:
    test-action:
      runs-on: ubuntu-latest
      steps:
       - name: list-files
         run: |
           pwd
           ls -aR
           echo $GITHUB_SHA
           echo $GITHUB_REPOSITORY
           echo $GITHUB_WORKSPACE
           echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
       - name: checkout
         uses: actions/checkout@v2.6.0     
       - name: list-files-after-checkout
         run: |
           pwd
           ls -aR
       - name: simple-js-action
         id: greet
         uses: actions/hello-world-javascript-action@v1.1
         with:
           who-to-greet: Snowy
       - name: Log greeting time
         run: echo "${{ steps.greet.outputs.time }}"
