name: Shell cmd

on: [push]

jobs:
    run-shell-cmd:
     runs-on: ubuntu-latest
     steps:
       - name: echo string
         run: echo "hello world"
      #  - name: multiline script
      #    run: |
      #      node -v
      #      npm -v
      #      python -v